### ISSUE TITLE
linting issues

### ISSUE THREAD

**Issue by pmstss** [abdes/happy-coding#1]
@abdes, firstly, thanks for useful repo! 

1) `npm run lint` lints only `example` project. But there are linting errors in other projects (e. g. `npm run lint ui-header`)

Afaik this behavior is result of recent `nx` updates and relates to `defaultProject` setting in `angular.json`. 
Do you know workaround, i. e. how to run lint on all projects, keeping `defaultProject` setting?

2) `@angular-eslint/template/no-negated-async` [is part]("@angular-eslint/template/no-negated-async": "error") of used `@angular-eslint/recommended` but `npm run lint` does not trigger error on violating this rule

**Comment by abdes** [comment]
You have two options:

1. Run linting on a specific project, you can always do `yarn lint xxx` where xxx is the project name. For example `yarn lint ui-header`.
2. With Nx, you have one more way to run lint for example on all projects:
```
yarn nx run-many --all --target lint
```

You can also leverage Nx dep-graph when you makes changes to run the target only on affected projects:

```
yarn affected:lint
```

I hope this answers your first question.

Regarding your issue with es-lint, as per https://github.com/angular-eslint/angular-eslint, yes it is included and supposed to have been implemented. Please keep in mind that the eslint and angular is still in beta, and the best way to report such issues is in the relevant repo issue trackers. I believe in this case, it should be https://github.com/angular-eslint/angular-eslint.

**Comment by pmstss** [comment]
@abdes, thanks!
`nx run-many --all --target lint` indeed solves the first question.
Regarding to the second I'm not sure is it nx or angular-eslint related - as in [angular-eslint sample](https://github.com/angular-eslint/angular-eslint/tree/master/packages/integration-tests/fixtures/angular-cli-workspace) mentioned `@angular-eslint/template/no-negated-async` works.

**Comment by abdes** [comment]
So, I did a small test for you. I added some code to the example app just to do what you are trying to. I run lint target and it DID report an error as expected. So you ma y be doing something wrong. 

The only thing that comes to mind is that if you are using an inline template, try to use an external template please. Inline template still cause issues and remember that angular/eslint is still experimental :-)

**app.component.ts**
```ts
  dataReady = new Subject<boolean>();
  dataReadyObs = this.dataReady.asObservable();

  ngOnInit(): void {
    setTimeout(() => {
      this.dataReady.next(true);
    }, 5000);
  }
```

**app.component.html**
```html
    <!-- This will trigger a linter error -->
    <h3 *ngIf="!(dataReadyObs | async)">
      Please wait (this message will disappear in 5 seconds) ...
    </h3>

    <!-- This will not trigger a linter error -->
    <!--
    <h3 *ngIf="(dataReadyObs | async) === false">
      Please wait (this message will disappear in 5 seconds) ...
    </h3>
    -->
```

```shell
happy-coding git: master ≣ env:PS>yarn lint
yarn run v1.22.4
$ nx workspace-lint && ng lint

> ng run example:lint 

Linting "example"...

E:\dev\projects\workspaces\happy-coding\apps\example\src\app\app.component.html
  26:16  error  Async pipes should not be negated. Use (observable | async) === (false | null | undefined) to check its value instead  @angular-eslint/template/no-negated-async

✖ 1 problem (1 error, 0 warnings)

```

```

**Comment by pmstss** [comment]
@abdes, thanks a lot for your tests and advices! 👍

Indeed `@angular-eslint/template/no-negated-async` work correctly on my second try, perhaps was some typo on first try, sorry for bothering.

Regarding to inline templates - no, I do not use them, but `angular-eslint` seems [support them](https://github.com/angular-eslint/angular-eslint/blob/44392627ecd2e2cd332f1a9f47c0fec8dfaa5e59/packages/integration-tests/fixtures/angular-cli-workspace/.eslintrc.js#L44). 

Btw, your sample observable initialization can be shortened to `dataReadyObs  = timer(5000).pipe(map(()=>true));`

**Comment by abdes** [comment]
`dataReadyObs = timer(5000).pipe(map(()=>true));` is much more elegant 👍

**Comment by abdes** [comment]
@pmstss should we close this one?

**Comment by pmstss** [comment]
seems so, thank you!
